baseURL: "https://erolserife.github.io/webseite/"
title: Şerife Erol
enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20
taxonomies:
    tag: tags
menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Book
          url: book/
          weight: 3
        - name: Courses
          url: courses/
          weight: 4
        - name: News
          url: news/
          weight: 5
params:
    description: "This website hosts Şerife Erol's research and teaching materials, curriculum vitae, and contact information."
    author: Şerife Erol
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Şerife Erol
          subtitle: "I am a postdoctoral researcher at the [Friedrich Schiller University Jena](https://www.uni-jena.de), specializing in labor relations, vocational training, and institutional transformation. My research focuses on industrial relations, the regulation of contingent labor, and workplace continuing education. I was previously a researcher at the [Institute of Economic and Social Research (WSI)](https://www.wsi.de), Hans Böckler Foundation. <br /> <br /> My [Curriculum Vitae](cv.pdf) has more detail, if you need it. Most of my [papers](papers) and my [book](book) are available on this site as well as information on my [courses](/courses)."
          imageUrl: "picture.jpeg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Papers
              url: papers/
            - name: Book
              url: book/
            - name: Courses
              url: courses/
            - name: News
              url: news/
            - name: Tags
              url: tags/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:s.erol@uni-jena.de
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Şerife Erol"
      icon: favicon.png
      iconHeight: 18
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
